/* Tabela de Combustíveis */
CREATE TABLE COMBUSTIVEIS (
    ID INTEGER NOT NULL,
    TIPO_COMBUSTIVEL VARCHAR(50) NOT NULL,
    PRECO_LITRO NUMERIC(10,3) NOT NULL,
    CONSTRAINT PK_COMBUSTIVEIS PRIMARY KEY (ID)
);

/* Tabela de Tanques */
CREATE TABLE TANQUES (
    ID INTEGER NOT NULL,
    ID_COMBUSTIVEL INTEGER NOT NULL,
    CONSTRAINT PK_TANQUES PRIMARY KEY (ID),
    CONSTRAINT FK_TANQUES_COMBUSTIVEIS FOREIGN KEY (ID_COMBUSTIVEL) REFERENCES COMBUSTIVEIS(ID)
);

/* Tabela de Bombas */
CREATE TABLE BOMBAS (
    ID INTEGER NOT NULL,
    ID_TANQUE INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_BOMBAS PRIMARY KEY (ID),
    CONSTRAINT FK_BOMBAS_TANQUES FOREIGN KEY (ID_TANQUE) REFERENCES TANQUES(ID)
);

/* Tabela de Abastecimentos */
CREATE TABLE ABASTECIMENTOS (
    ID INTEGER NOT NULL,
    ID_BOMBA INTEGER NOT NULL,
    DATA_ABASTECIMENTO TIMESTAMP NOT NULL,
    LITROS NUMERIC(10,3) NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    IMPOSTO NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_ABASTECIMENTOS PRIMARY KEY (ID),
    CONSTRAINT FK_ABASTECIMENTOS_BOMBAS FOREIGN KEY (ID_BOMBA) REFERENCES BOMBAS(ID)
);

/* Sequences para geração de IDs */
CREATE SEQUENCE GEN_COMBUSTIVEIS_ID;
CREATE SEQUENCE GEN_TANQUES_ID;
CREATE SEQUENCE GEN_BOMBAS_ID;
CREATE SEQUENCE GEN_ABASTECIMENTOS_ID;

/* Triggers para auto-incremento */
SET TERM ^ ;

CREATE TRIGGER COMBUSTIVEIS_BI FOR COMBUSTIVEIS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_COMBUSTIVEIS_ID,1);
END
^

CREATE TRIGGER TANQUES_BI FOR TANQUES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TANQUES_ID,1);
END
^

CREATE TRIGGER BOMBAS_BI FOR BOMBAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_BOMBAS_ID,1);
END
^

CREATE TRIGGER ABASTECIMENTOS_BI FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ABASTECIMENTOS_ID,1);
END
^

SET TERM ; ^

/* Inserção de dados iniciais */
INSERT INTO COMBUSTIVEIS (ID, TIPO_COMBUSTIVEL, PRECO_LITRO) VALUES (1, 'Gasolina', 5.890);
INSERT INTO COMBUSTIVEIS (ID, TIPO_COMBUSTIVEL, PRECO_LITRO) VALUES (2, 'Oleo Diesel', 5.490);

INSERT INTO TANQUES (ID, ID_COMBUSTIVEL) VALUES (1, 1);
INSERT INTO TANQUES (ID, ID_COMBUSTIVEL) VALUES (2, 2);

INSERT INTO BOMBAS (ID, ID_TANQUE, NUMERO, NOME) VALUES (1, 1, 1, 'Bomba 1');
INSERT INTO BOMBAS (ID, ID_TANQUE, NUMERO, NOME) VALUES (2, 1, 2, 'Bomba 2');
INSERT INTO BOMBAS (ID, ID_TANQUE, NUMERO, NOME) VALUES (3, 2, 3, 'Bomba 3');
INSERT INTO BOMBAS (ID, ID_TANQUE, NUMERO, NOME) VALUES (4, 2, 4, 'Bomba 4');

COMMIT;

